### ISSUE TITLE
Maybe custom component to map cities to Bundesländer?

### ISSUE THREAD

**Issue by lislis** [feminizidmap/feminizidmap-backend#35]
Im Excel hat es jemensch geschafft eine Liste mit Städten zu ihren Bundesländern zu mappen. dh wenn mensch eine Stadt ausgewählt hat wurde in der Spalte Bundesland das dementsprechend ausgefüllt.

Wie schwer wäre das als Stapi plugin umzusetzen? Die Listen haben wir im Excel, es geht darum das als nices Interface umzubauen?

**Comment by andneuma** [comment]
Also du meinst, dass automatisch das Bundesland ausgefüllt wird auf Grundlage der Stadt?

**Comment by andneuma** [comment]
@lislis Also so, dass Leute dann nur Stadt und PLZ und vlt noch Straße etc angeben?

**Comment by lislis** [comment]
genau!

**Comment by andneuma** [comment]
ok, kann ich machen

**Comment by andneuma** [comment]
Ah nee, dis wird schwierig glaube ich weil PLZ nicht eingteragen wird womit wir dann kein eindeutiges identifier paar haben. gibt nur freitext. Meine Befürchtung wäre, dass zudem leute sich verschreiben

![image](https://github.com/feminizidmap/feminizidmap-backend/assets/12527312/15df0506-711a-4228-a95e-da8e2c7c96ff)

https://forum.strapi.io/t/lifecycle-and-components-inside-collections-type/14003/13

**Comment by lislis** [comment]
hmm, also wäre plz als Feld hinzuzufügen deiner Meinung nach nicht genug? Was wäre die alternative?

**Comment by andneuma** [comment]
achso, doch, missverständnis! also du meinst das plz feld würde noch dazu kommen? weil dann reichts, klaro! dh die information gibts eigentlich immer, nur das bundesland rauspuzzlen is so ein nerviger extra step? also sehe auf jeden fall, dass das sinn macht. kann das feld dann einfach mit dazu nehmen und via regex auf german postal code format einschränken

**Comment by andneuma** [comment]
ok, also das scheint irgendwie komplizierter als gedacht und mir schleierhaft wie man das gescheit in Strapi macht ehrlich gesagt :/ Das Problem liegt im Update von properties innerhalb von single / repeatable components. Vlt merken wir uns das einfach, v5 ist in der Betaphase und geht das Problem vielleicht an?

**Comment by lislis** [comment]
okay! dann überleg ich mir mal wie ich erkläre warum das in der Excel einfach ging und in strapi nicht 😅 #computerthings

**Comment by andneuma** [comment]
viel erfolg 😅 aber vlt bevor du das machst: ich frag nochmal im strapi forum explizit nach, vlt kommt da ja noch was bei rum. solang können wir das issue ja offen lassen

**Comment by lislis** [comment]
Hier auch ein kleiner Pivot-Vorschlag: Anstatt des automatisierten mappings von Stadt auf Bundesland, zumindest die Stadt/Landkreis Liste aus dem Excel in ein Dropdown zu importieren, das als relation zu nutzen?
Damit wir auf jeden Fall erstmal vermeiden, dass Stadt/LAndkreis Freitextfeld ist und damit sehr fehleranfällig.
@andneuma können wir dein import-script vereinfacht dafür nutzen?

**Comment by lislis** [comment]
see #49

**Comment by lislis** [comment]
Nicht mehr relevant mit neuem City-Landkreis-Dropdown am Start
