### ISSUE TITLE
Add annotations for address fields

### ISSUE THREAD

**Issue by lislis** [feminizidmap/feminizidmap-backend#39]
- don't add victim and/or perp address if they're the same as the crime address
- if the address is different but unknown create an address but leave it empty

@andneuma Wir können vermutlich zwischen nicht-existierender Address-Component und existierender aber leerer Adress-Component unterscheiden, oder?

**Comment by andneuma** [comment]
@lislis bezieht sich das auf Strapi oder den Import?

**Comment by lislis** [comment]
Auf das Anlegen eines Datenpunkts bzw wenn wir die public api schreiben

**Comment by andneuma** [comment]
@lislis Im Anschluss an die vorrübergehenden Rechercheergbnisse (siehe #35) scheint das leider etwas komplizierter zu sein :/ Ich schau mal ob sich da noch so hackishe Lösungen finden lassen (also zB afterCreate via REST calls modifikationen am Record vorzunehmen)

**Comment by lislis** [comment]
@andneuma dann schieben wir das Problem zu Zukunfts-Wir:tm: und dann erkläre ich das System wie im original Kommentar beschrieben und wir hoffen wir können das irgendwann rauspopeln?

**Comment by lislis** [comment]
Nicht mehr relevant, weil neue Adresse/ Stadt-Landkreis-Dropdown am Start
