### ISSUE TITLE
Question: auto-save when entering a case?

### ISSUE THREAD

**Issue by lislis** [feminizidmap/feminizidmap-backend#42]
@andneuma Gibt es ein auto-save plugin oder hast du in diese richtung Erfahrung(en)? Leute waren ein bisschen nervös, dass sie immer dran denken müssen "save" zu drücken 😬

**Comment by andneuma** [comment]
Es gibt für Chrome [dieses](https://chromewebstore.google.com/detail/strapi-auto-save-for-draf/ocggajfofjhnpbfkaglecgmakdjgddnb) Plugin. Für Firefox + Safari scheinbar nicht. Gibt auch kein Plugin. Also vielleicht einfach den Leuten empfehlen für die Strapi Sessions Chrome / Chromium zu verwenden?

**Comment by lislis** [comment]
hmmm, ich würde dann einfach sagen "auto save geht nicht", weil mit extra plugins und nur ins bestimmten browsern ist schwierig zu kommunizieren und (menschlich) zu supporten. aber danke für die recherche! Ich close das mal so
